######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "la Discipline du Jeu"
theme = "restaurant-hugo"
summaryLength = "7"
paginate = 6

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Accueil"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Édito"
URL = "about-us"
weight = 2

[[menu.main]]
name = "News"
URL = "blog"
weight = 3

[[menu.main]]
name = "École (2020/2021)"
URL = "price"
weight = 4

[[menu.main]]
name = "Spectacles"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Contact"
URL = "footer"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "TeDua"
description = "Site web de l'association de pratique de la discipline du jeu (théâtre,clown) TeDua."
# google analitycs ID
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyleft 2020 - Habib Belaribi - theme: Themefisher.com"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT : "
blogTitle = "NEWS :"
galleryTitle = "IMAGES : "
socialTitle = "ACTIVITÉS et VIE ASSOCIATIVE : "

############################ footer contact item
[[params.footer.contactItem]]
title="Téléphone"
icon = "fa fa-phone"
content = "06 15 60 97 04 (Anne Lucie Dumay)"
[[params.footer.contactItem]]
title="Adresse"
icon = "fa fa-map-marker"
content = "50 rue du Mirail 33000 Bordeaux"

[[params.footer.contactItem]]
title="Email"
icon = "fa fa-envelope"
content = "ecole@association-tedua.fr ou diffusion@association-tedua.fr"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/Petites-accueil-2.png"

[[params.footer.gallery]]
image = "images/slider/Petites-accueil-1.png"

[[params.footer.gallery]]
image = "images/slider/Petites-accueil-4.png"

[[params.footer.gallery]]
image = "images/slider/Petites-accueil-11.png"

[[params.footer.gallery]]
image = "images/slider/Petites-accueil-6.png"

[[params.footer.gallery]]
image = "images/slider/Petites-accueil-7.png"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/groups/386241745191819/"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/anneluciedumay/?hl=en"

#[[params.footer.socialLink]]
#icon = "twitter"
#link = "https://twitter.com/habsinn"
